name: Checkmarx Scan with Tags

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkmarx AST GitHub Action
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          base_uri: https://us.ast.checkmarx.net
          cx_tenant: ${{ secrets.CX_TENANT }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: ""
